name: Reusing Workflow

on: [workflow_dispatch]

jobs:
  call-workflow:
    uses: ./.github/workflows/reusable-workflow.yml
    with:
      who-to-greet: 'Martin'
      
  use-output:
    runs-on: ubuntu-latest
    needs: [call-workflow]
    steps:
      - run: echo "Time was ${{ needs.call-workflow.outputs.current-time }}"
